name: .NET Core
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install SonarQube
      run: dotnet tool install --global dotnet-sonarscanner
    - name: Start SonarQube
      run: dotnet sonarscanner begin /k:"DuAell_FolderBackup" /o:"duaell" /d:sonar.host.url="https://sonarcloud.io"
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: End SonarQube
      run: dotnet sonarscanner end
